version: '3.8'
services:
  myapp:
    depends_on:
      - mysqldb
    container_name: serino-tech-exam
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT=${PORT}
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/myapp/dev
      - exclude:/usr/local/apps/myapp/dev/node_modules/
    links: 
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=serino_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  exclude: